#!/usr/bin/env python
# vim: set ts=4 sw=4 tw=99 et:

# iongraph -- Translate IonMonkey JSON to GraphViz.
# Copyright 2011-2012, Sean Stangl <sstangl@mozilla.com>

import json
import sys
import cgi

def quote(s):
    return '"%s"' % str(s)

# Simple classes for the used subset of GraphViz' Dot format.
# There are more complicated constructors out there, but they all
# pull in annoying dependencies (and are annoying dependencies themselves).
class GraphWidget:
    def __init__(self):
        self.name = ''
        self.props = {}

    def addprops(self, propdict):
        for p in propdict:
            self.props[p] = propdict[p]


class Node(GraphWidget):
    def __init__(self, name):
        GraphWidget.__init__(self)
        self.name = str(name)

class Edge(GraphWidget):
    def __init__(self, nfrom, nto):
        GraphWidget.__init__(self)
        self.nfrom = str(nfrom)
        self.nto = str(nto)

class Graph(GraphWidget):
    def __init__(self, name, type):
        GraphWidget.__init__(self)
        self.name = name
        self.type = str(type)
        self.props = {}
        self.nodes = []
        self.edges = []

    def addnode(self, n):
        self.nodes.append(n)

    def addedge(self, e):
        self.edges.append(e)

    def writeprops(self, f, o):
        if len(o.props) == 0:
            return

        print >> f, '[',
        for p in o.props:
            print >> f, str(p) + '=' + str(o.props[p]),
        print >> f, ']',

    def write(self, f):
        print >> f, self.type, '{'
        
        # Output graph properties.
        for p in self.props:
            print >> f, '  ' + str(p) + '=' + str(self.props[p])
        print >> f, ''

        # Output node list.
        for n in self.nodes:
            print >> f, '  ' + n.name,
            self.writeprops(f, n)
            print >> f, ';'
        print >> f, ''
        
        # Output edge list.
        for e in self.edges:
            print >> f, '  ' + e.nfrom, '->', e.nto,
            self.writeprops(f, e)
            print >> f, ';'

        print >> f, '}'


# block obj -> node string with quotations
def getBlockNodeName(b):
    return blockNumToNodeName(b['number'])

# int -> node string with quotations
def blockNumToNodeName(i):
    return quote('Block' + str(i))

# resumePoint obj -> HTML-formatted string
def getResumePointRow(rp, mode):
    if mode != None and mode != rp['mode']:
        return ''

    # Left column: caller.
    rpCaller = '<td align="left"></td>'
    if 'caller' in rp:
        rpCaller = '<td align="left">&#40;&#40;%s&#41;&#41;</td>' % str(rp['caller'])

    # Middle column: ordered contents of the MResumePoint.
    insts = ''.join('%s ' % t for t in rp['operands'])
    rpContents = '<td align="left"><font color="grey50">resumepoint %s</font></td>' % insts

    # Right column: unused.
    rpRight = '<td></td>'

    return '<tr>%s%s%s</tr>' % (rpCaller, rpContents, rpRight)

# Outputs a single row for an instruction, excluding MResumePoints.
# instruction -> HTML-formatted string
def getInstructionRow(inst):
    # Left column: instruction ID.
    instId = str(inst['id'])
    instLabel = '<td align="right" port="i%s">%s</td>' % (instId, instId)

    # Middle column: instruction name.
    instName = cgi.escape(inst['opcode'])
    if 'attributes' in inst:
        if 'Movable' in inst['attributes']:
            instName = '<font color="blue">%s</font>' % instName
        if 'NeverHoisted' in inst['attributes']:
            instName = '<u>%s</u>' % instName
    instName = '<td align="left">%s</td>' % instName

    # Right column: instruction MIRType.
    instType = ''
    if 'type' in inst and inst['type'] != "None":
        instType = '<td align="left">%s</td>' % cgi.escape(inst['type'])

    return '<tr>%s%s%s</tr>' % (instLabel, instName, instType)

# block obj -> HTML-formatted string
def getBlockLabel(b):
    s =  '<<table border="0" cellborder="0" cellpadding="1">'

    if 'blockUseCount' in b:
        blockUseCount = str(b['blockUseCount'])
    else:
        blockUseCount = 'N/A'

    blockTitle = '<font color="white">Block %s (Count: %s)</font>' % \
            (str(b['number']), blockUseCount)
    blockTitle = '<td align="center" bgcolor="black" colspan="3">%s</td>' % blockTitle
    s += '<tr>%s</tr>' % blockTitle
    
    if 'resumePoint' in b:
        s += getResumePointRow(b['resumePoint'], None)

    for inst in b['instructions']:
        if 'resumePoint' in inst:
            s += getResumePointRow(inst['resumePoint'], 'At')

        s += getInstructionRow(inst)

        if 'resumePoint' in inst:
            s += getResumePointRow(inst['resumePoint'], 'After')

    s += '</table>>'
    return s

# str -> ir obj -> ir obj -> Graph
# 'ir' is the IR to be used.
# 'mir' is always the MIR.
#  This is because the LIR graph does not contain successor information.
def buildGraphForIR(name, ir, mir):
    if len(ir['blocks']) == 0:
        return None

    g = Graph(name, 'digraph')
    g.addprops({'rankdir':'TB', 'splines':'true'})

    for i in range(0, len(ir['blocks'])):
        bactive = ir['blocks'][i] # Used for block contents.
        b = mir['blocks'][i] # Used for drawing blocks and edges.

        node = Node(getBlockNodeName(bactive))
        node.addprops({'shape':'box', 'label':getBlockLabel(bactive)})
        
        if 'backedge' in b['attributes']:
            node.addprops({'color':'red'})
        if 'loopheader' in b['attributes']:
            node.addprops({'color':'green'})
        if 'splitedge' in b['attributes']:
            node.addprops({'style':'dashed'})

        g.addnode(node)

        for succ in b['successors']: # which are integers
            edge = Edge(getBlockNodeName(bactive), blockNumToNodeName(succ))
                
            if len(b['successors']) == 2:
                if succ == b['successors'][0]:
                    edge.addprops({'label':'1'})
                else:
                    edge.addprops({'label':'0'})

            g.addedge(edge)

    return g

# pass obj -> output file -> (Graph OR None, Graph OR None)
# The return value is (MIR, LIR); either one may be absent.
def buildGraphsForPass(p):
    name = p['name']
    mir = p['mir']
    lir = p['lir']
    return (buildGraphForIR(name, mir, mir), buildGraphForIR(name, lir, mir))

# function obj -> (Graph OR None, Graph OR None) list
# First entry in each tuple corresponds to MIR; second, to LIR.
def buildGraphs(func):
    graphstup = []
    for p in func['passes']:
        gtup = buildGraphsForPass(p)
        graphstup.append(gtup)
    return graphstup

# function obj -> (Graph OR None, Graph OR None) list
# Only builds the final pass.
def buildOnlyFinalPass(func):
    if len(func['passes']) == 0:
        return [None, None]
    p = func['passes'][-1]
    return [buildGraphsForPass(p)]

# Write out a graph, constructing a nice filename.
# function id -> pass id -> IR string -> Graph -> void
def outputPass(fnum, pnum, irname, g):
    funcid = str(fnum).zfill(2)
    passid = str(pnum).zfill(2)

    filename = 'func%s-pass%s-%s-%s.gv' % (funcid, passid, g.name, str(irname))

    f = open(filename, 'w')
    g.write(f)
    f.close()

# Add in closing } and ] braces to close a JSON file in case of error.
def parenthesize(s):
    stack = []
    inString = False

    for c in s:
        if c == '"': # Doesn't handle escaped strings.
            inString = not inString

        if not inString:
            if   c == '{' or c == '[':
                stack.append(c)
            elif c == '}' or c == ']':
                stack.pop()
    
    while stack:
        c = stack.pop()
        if   c == '{': s += '}'
        elif c == '[': s += ']'

    return s

def dieWithUsage():
    sys.stderr.write(" Usage: " + sys.argv[0] + " [--final] [--funcnum N] <JSON file>\n")
    sys.exit(1)

def main():
# Operate on provided file.
    import sys
    args = list(sys.argv)

    # Get rid of program name.
    args.pop(0)

    # --help option: die with some output.
    for i in range(0, len(args)):
        if args[i] == '--help' or args[i] == '-h':
            dieWithUsage()

    # --final option: only generate the last MIR/LIR.
    optFinal = False
    for i in range(0, len(args)):
        if args[i] == '--final':
            optFinal = True
            args.pop(i)
            break

    # --funcnum N option: only operate on the provided function, by index.
    optFunc = -1
    for i in range(0, len(args)):
        if args[i] == '--funcnum':
            try:
                optFunc = int(args[i+1])
            except e:
                dieWithUsage()
            args.pop(i)
            args.pop(i)
            break

    # Last remaining option in args should be the mandatory input filename.
    if len(args) != 1:
        dieWithUsage()
    argFilename = args[0]


    f = open(argFilename, 'r')
    s = f.read()
    f.close()

    ion = json.loads(parenthesize(s))

    for i in range(0, len(ion['functions'])):
        func = ion['functions'][i]

        if optFunc >= 0 and i != optFunc:
            continue

        gtl = []
        if optFinal:
            gtl = buildOnlyFinalPass(func)
        else:
            gtl = buildGraphs(func)

        if len(gtl) == 0:
            sys.stderr.write(" function %d (%s): abort during SSA construction.\n" % (i, func['name']))
        else:
            sys.stderr.write(" function %d (%s): success; %d passes.\n" % (i, func['name'], len(gtl)))

        for j in range(0, len(gtl)):
            gt = gtl[j]
            if gt == None:
                continue

            mir = gt[0]
            lir = gt[1]

            # If only the final pass is requested, output both MIR and LIR.
            if optFinal:
                if lir != None:
                    outputPass(i, j, 'lir', lir)
                if mir != None:
                    outputPass(i, j, 'mir', mir)
                continue

            # Normally, only output one of (MIR, LIR), preferring LIR.
            if lir != None:
                outputPass(i, j, 'lir', lir)
            elif mir != None:
                outputPass(i, j, 'mir', mir)

if __name__ == '__main__':
    main()

