#!/usr/bin/env python
#
# Reads in IonMonkey JSON files.
# Outputs useful graphical descriptions of those files in GraphViz format.
# Runs those files through GraphViz.
#
# Copyright 2011, Sean Stangl <sstangl@mozilla.com>
#

import json
import sys
import cgi

def quote(s): return '"' + str(s) + '"'

# Simple classes for the used subset of GraphViz' Dot format.
# There are more complicated constructors out there, but they all
# pull in annoying dependencies (and are annoying dependencies themselves).
class GraphWidget:
	def __init__(self):
		self.name = ''
		self.props = {}

	def addprops(self, propdict):
		for p in propdict:
			self.props[p] = propdict[p]


class Node(GraphWidget):
	def __init__(self, name):
		GraphWidget.__init__(self)
		self.name = str(name)

class Edge(GraphWidget):
	def __init__(self, nfrom, nto):
		GraphWidget.__init__(self)
		self.nfrom = str(nfrom)
		self.nto = str(nto)

class Graph(GraphWidget):
	def __init__(self, name, type):
		GraphWidget.__init__(self)
		self.name = name
		self.type = str(type)
		self.props = {}
		self.nodes = []
		self.edges = []

	def addnode(self, n):
		self.nodes.append(n)

	def addedge(self, e):
		self.edges.append(e)

	def writeprops(self, f, o):
		if len(o.props) == 0:
			return

		print >> f, '[',
		for p in o.props:
			print >> f, str(p) + '=' + str(o.props[p]),
		print >> f, ']',

	def write(self, f):
		print >> f, self.type, '{'
		
		# Output graph properties.
		for p in self.props:
			print >> f, '  ' + str(p) + '=' + str(self.props[p])
		print >> f, ''

		# Output node list.
		for n in self.nodes:
			print >> f, '  ' + n.name,
			self.writeprops(f, n)
			print >> f, ';'
		print >> f, ''
		
		# Output edge list.
		for e in self.edges:
			print >> f, '  ' + e.nfrom, '->', e.nto,
			self.writeprops(f, e)
			print >> f, ';'

		print >> f, '}'


# inst -> string with quotation marks
def getInstructionName(inst):
	return '"(' + str(inst['id']) + ') ' + inst['opcode'] + '"'

# block obj -> node string with quotations
def getBlockNodeName(b):
	return blockNumToNodeName(b['number'])

# int -> node string with quotations
def blockNumToNodeName(i):
	return quote('Block' + str(i))

# block obj -> HTML-formatted string
def getBlockLabel(b):
	s =  '<<table border="0" cellborder="0" cellpadding="1">'
	s +=   '<tr><td align="center" bgcolor="black" colspan="3">'
	s +=     '<font color="white">Block ' + str(b['number']) + '</font>'  
	s +=   '</td></tr>'

	for inst in b['instructions']:
		hasattributes = 'attributes' in inst
		idempotent = hasattributes and 'Idempotent' in inst['attributes']

		s += '<tr>'
		s +=   '<td align="left" port="i' + str(inst['id']) + '">'
		s +=     '&#40;' # left parenthesis
		s +=     str(inst['id'])
		s +=     '&#41;' # right parenthesis
		s +=   '</td>'

		s +=   '<td align="left">'
		if idempotent:
			s += '<font color="blue">' + cgi.escape(inst['opcode']) + '</font>'
		else:
			s += cgi.escape(inst['opcode'])
		s +=   '</td>'

		if 'type' in inst and inst['type'] != "None":
			s +=   '<td align="left">'
			s +=     cgi.escape(inst['type'])
			s +=   '</td>'
		s += '</tr>'

	s += '</table>>'
	return s

# str -> ir obj -> ir obj -> Graph
# 'ir' is the IR to be used.
# 'mir' is always the MIR.
#  This is because the LIR graph does not contain successor information,
#  but it's the same as 
def buildGraphForIR(name, ir, mir):
	if len(ir['blocks']) == 0:
		return None

	g = Graph(name, 'digraph')
	g.addprops({'rankdir':'TB', 'splines':'true'})

	for i in range(0, len(ir['blocks'])):
		bactive = ir['blocks'][i] # Used for block contents.
		b = mir['blocks'][i] # Used for drawing blocks and edges.

		node = Node(getBlockNodeName(bactive))
		node.addprops({'shape':'box', 'label':getBlockLabel(bactive)})
		
		if 'backedge' in b['attributes']:
			node.addprops({'color':'red'})
		if 'loopheader' in b['attributes']:
			node.addprops({'color':'green'})
		if 'splitedge' in b['attributes']:
			node.addprops({'style':'dashed'})

		g.addnode(node)

		for succ in b['successors']: # which are integers
			edge = Edge(getBlockNodeName(bactive), blockNumToNodeName(succ))
				
			if len(b['successors']) == 2:
				if succ == b['successors'][0]:
					edge.addprops({'label':'1'})
				else:
					edge.addprops({'label':'0'})

			g.addedge(edge)

	return g

# pass obj -> output file -> (Graph OR None, Graph OR None)
# The return value is (MIR, LIR); either one may be absent.
def buildGraphsForPass(p):
	name = p['name']
	mir = p['mir']
	lir = p['lir']
	return (buildGraphForIR(name, mir, mir), buildGraphForIR(name, lir, mir))

# function obj -> output file -> (Graph OR None, Graph OR None) list
# First entry in each tuple corresponds to MIR; second, to LIR.
def buildGraphs(func):
	graphstup = []
	for p in func['passes']:
		gtup = buildGraphsForPass(p)
		graphstup.append(gtup)

	return graphstup


# Write out a graph, constructing a nice filename.
# function id -> pass id -> IR string -> Graph -> void
def outputPass(fnum, pnum, irname, g):
	filename  = 'func' + str(fnum)
	filename += '-pass' + str(pnum)
	filename += '-' + str(irname)
	filename += '-' + g.name
	filename += '.gv'

	f = open(filename, 'w')
	g.write(f)
	f.close()

# Operate on provided file.
if __name__ == '__main__':
	from sys import argv

	if len(argv) != 2:
		sys.stderr.write(" Usage: " + sys.argv[0] + " <JSON file>\n")
		sys.exit(1)

	f = open(argv[1], 'r')
	ion = json.load(f)
	f.close()

	for i in range(0, len(ion['functions'])):
		func = ion['functions'][i]
		gtl = buildGraphs(func)
		for j in range(0, len(gtl)):
			gt = gtl[j]
			mir = gt[0]
			lir = gt[1]

			# Only output one of (MIR, LIR). Prefer LIR.
			# This is just to avoid spam; change if you care about it.
			if lir != None:
				outputPass(i, j, 'lir', lir)
			elif mir != None:
				outputPass(i, j, 'mir', mir)

